// <auto-generated />
using System;
using FilunK.backenddotnet_trial.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace backenddotnet_trial.Migrations
{
    [DbContext(typeof(PgContext))]
    [Migration("20190831000327_initial_2")]
    partial class initial_2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("FilunK.backenddotnet_trial.DataAccess.DataModel.AccountConfirm", b =>
                {
                    b.Property<string>("ConfirmUri")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("confirm_uri")
                        .HasMaxLength(40);

                    b.Property<DateTime>("CreationDate")
                        .HasColumnName("creation_date");

                    b.Property<string>("CreationId")
                        .IsRequired()
                        .HasColumnName("creation_id")
                        .HasMaxLength(30);

                    b.Property<string>("CreationProgram")
                        .IsRequired()
                        .HasColumnName("creation_pg")
                        .HasMaxLength(30);

                    b.Property<DateTime>("ExpireLimit")
                        .HasColumnName("expire_limit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnName("del_flg");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnName("update_date");

                    b.Property<string>("UpdateId")
                        .IsRequired()
                        .HasColumnName("update_id")
                        .HasMaxLength(30);

                    b.Property<string>("UpdateProgram")
                        .IsRequired()
                        .HasColumnName("update_pg")
                        .HasMaxLength(30);

                    b.Property<string>("UserId")
                        .HasColumnName("user_id")
                        .HasMaxLength(100);

                    b.HasKey("ConfirmUri");

                    b.ToTable("wk_account_confirm","bk_dotnet");
                });

            modelBuilder.Entity("FilunK.backenddotnet_trial.DataAccess.DataModel.Book", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnName("user_id")
                        .HasMaxLength(100);

                    b.Property<string>("Isbn")
                        .HasColumnName("isbn_13")
                        .HasMaxLength(13);

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnName("author");

                    b.Property<string>("Comment")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnName("creation_date");

                    b.Property<string>("CreationId")
                        .IsRequired()
                        .HasColumnName("creation_id")
                        .HasMaxLength(30);

                    b.Property<string>("CreationProgram")
                        .IsRequired()
                        .HasColumnName("creation_pg")
                        .HasMaxLength(30);

                    b.Property<bool>("IsDeleted")
                        .HasColumnName("del_flg");

                    b.Property<int>("PageCount")
                        .HasColumnName("page_count");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnName("purchase_date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnName("update_date");

                    b.Property<string>("UpdateId")
                        .IsRequired()
                        .HasColumnName("update_id")
                        .HasMaxLength(30);

                    b.Property<string>("UpdateProgram")
                        .IsRequired()
                        .HasColumnName("update_pg")
                        .HasMaxLength(30);

                    b.HasKey("UserId", "Isbn");

                    b.ToTable("t_book","bk_dotnet");
                });

            modelBuilder.Entity("FilunK.backenddotnet_trial.DataAccess.DataModel.User", b =>
                {
                    b.Property<string>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("user_id")
                        .HasMaxLength(100);

                    b.Property<DateTime>("CreationDate")
                        .HasColumnName("creation_date");

                    b.Property<string>("CreationId")
                        .IsRequired()
                        .HasColumnName("creation_id")
                        .HasMaxLength(30);

                    b.Property<string>("CreationProgram")
                        .IsRequired()
                        .HasColumnName("creation_pg")
                        .HasMaxLength(30);

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnName("hash");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnName("account_confirmed");

                    b.Property<bool>("IsDeleted")
                        .HasColumnName("del_flg");

                    b.Property<int>("Iteration")
                        .HasColumnName("iteration");

                    b.Property<string>("MailAddress")
                        .IsRequired()
                        .HasColumnName("mail_address");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnName("salt");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnName("update_date");

                    b.Property<string>("UpdateId")
                        .IsRequired()
                        .HasColumnName("update_id")
                        .HasMaxLength(30);

                    b.Property<string>("UpdateProgram")
                        .IsRequired()
                        .HasColumnName("update_pg")
                        .HasMaxLength(30);

                    b.HasKey("UserId");

                    b.ToTable("t_user","bk_dotnet");
                });
#pragma warning restore 612, 618
        }
    }
}
