// <auto-generated />
using System;
using FilunK.backenddotnet_trial.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace backenddotnet_trial.Migrations
{
    [DbContext(typeof(PgContext))]
    [Migration("20190811080402_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("FilunK.backenddotnet_trial.DataAccess.DataModel.AccountConfirm", b =>
                {
                    b.Property<string>("ConfirmUri")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("CONFIRM_URI")
                        .HasMaxLength(40);

                    b.Property<DateTime>("CreationDate")
                        .HasColumnName("CREATION_DATE");

                    b.Property<string>("CreationId")
                        .IsRequired()
                        .HasColumnName("CREATION_ID")
                        .HasMaxLength(30);

                    b.Property<string>("CreationProgram")
                        .IsRequired()
                        .HasColumnName("CREATION_PG")
                        .HasMaxLength(30);

                    b.Property<DateTime>("ExpireLimit")
                        .HasColumnName("EXPIRE_LIMIT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnName("DEL_FLAG");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnName("UPDATE_DATE");

                    b.Property<string>("UpdateId")
                        .IsRequired()
                        .HasColumnName("UPDATE_ID")
                        .HasMaxLength(30);

                    b.Property<string>("UpdateProgram")
                        .IsRequired()
                        .HasColumnName("UPDATE_ID")
                        .HasMaxLength(30);

                    b.Property<string>("UserId")
                        .HasColumnName("USER_ID");

                    b.HasKey("ConfirmUri");

                    b.ToTable("WK_ACCOUNT_CONFIRM","BK_DOTNET");
                });

            modelBuilder.Entity("FilunK.backenddotnet_trial.DataAccess.DataModel.User", b =>
                {
                    b.Property<string>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("USER_ID");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnName("CREATION_DATE");

                    b.Property<string>("CreationId")
                        .IsRequired()
                        .HasColumnName("CREATION_ID")
                        .HasMaxLength(30);

                    b.Property<string>("CreationProgram")
                        .IsRequired()
                        .HasColumnName("CREATION_PG")
                        .HasMaxLength(30);

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnName("HASH");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnName("ACCOUNT_CONFIRMED");

                    b.Property<bool>("IsDeleted")
                        .HasColumnName("DEL_FLAG");

                    b.Property<int>("Iteration")
                        .HasColumnName("ITERATION");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnName("SALT");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnName("UPDATE_DATE");

                    b.Property<string>("UpdateId")
                        .IsRequired()
                        .HasColumnName("UPDATE_ID")
                        .HasMaxLength(30);

                    b.Property<string>("UpdateProgram")
                        .IsRequired()
                        .HasColumnName("UPDATE_ID")
                        .HasMaxLength(30);

                    b.HasKey("UserId");

                    b.ToTable("T_USER","BK_DOTNET");
                });
#pragma warning restore 612, 618
        }
    }
}
